name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Entrar no frontend
        run: cd frontend

      - name: Instalar dependências
        run: |
          cd frontend
          npm install

      - name: Build do projeto
        run: |
          cd frontend
          npm run build